import React, { useState } from 'react'
import { createRoot } from 'react-dom/client'
import * as Select from '@radix-ui/react-select'
import * as Popover from '@radix-ui/react-popover'
import { DayPicker } from 'react-day-picker'
import { Check, ChevronDown, CalendarDays } from 'lucide-react'
import 'react-day-picker/style.css'

const prices = { Gold: { Interior: 130, Full: 160 }, Titanium: { Interior: 170, Full: 200 } }
const timeOptions = ['8:00 AM', '9:00 AM', '10:00 AM', '11:00 AM', '12:00 PM', '1:00 PM', '2:00 PM', '3:00 PM', '4:00 PM', '5:00 PM']
const readableDate = (date) => date ? new Intl.DateTimeFormat('en-CA', { weekday: 'short', month: 'short', day: 'numeric', year: 'numeric' }).format(date) : 'Select a date'

function FieldError({ message }) { return message ? <small className="field-error">{message}</small> : null }
function ShadSelect({ value, onChange, options, placeholder, error }) {
  return <><Select.Root value={value} onValueChange={onChange}><Select.Trigger className={'shad-trigger' + (error ? ' has-error' : '')} aria-label={placeholder}><Select.Value placeholder={placeholder} /><Select.Icon><ChevronDown size={17} /></Select.Icon></Select.Trigger><Select.Portal><Select.Content className="shad-content" position="popper" sideOffset={6}><Select.Viewport>{options.map(option => <Select.Item className="shad-item" value={option} key={option}><Select.ItemText>{option}</Select.ItemText><Select.ItemIndicator><Check size={15} /></Select.ItemIndicator></Select.Item>)}</Select.Viewport></Select.Content></Select.Portal></Select.Root><FieldError message={error} /></>
}
function DatePicker({ value, onChange, error }) {
  return <><Popover.Root><Popover.Trigger asChild><button type="button" className={'shad-trigger date-trigger' + (error ? ' has-error' : '')}><span className={value ? '' : 'placeholder'}>{readableDate(value)}</span><CalendarDays size={17} /></button></Popover.Trigger><Popover.Portal><Popover.Content className="calendar-popover" sideOffset={6} align="start"><DayPicker mode="single" selected={value} onSelect={onChange} disabled={{ before: new Date() }} /></Popover.Content></Popover.Portal></Popover.Root><FieldError message={error} /></>
}
function BookingForm() {
  const query = new URLSearchParams(window.location.search)
  const [values, setValues] = useState({ name:'', phone:'', instagram:'', vehicle:'', package: prices[query.get('package')] ? query.get('package') : 'Gold', serviceType: prices[prices[query.get('package')] ? query.get('package') : 'Gold'][query.get('type')] ? query.get('type') : 'Interior', location:'', serviceLocation:'', date:undefined, time:'', notes:'' })
  const [errors, setErrors] = useState({}); const [submitted, setSubmitted] = useState(false)
  const set = (key, value) => setValues(current => ({ ...current, [key]: value }))
  const submit = (event) => { event.preventDefault(); const next={}; [['name','Full Name'],['phone','Phone Number'],['vehicle','Vehicle Type'],['location','Service Location / Area'],['serviceLocation','Preferred Service Type'],['date','Preferred Date'],['time','Preferred Time']].forEach(([key,label])=>{if(!values[key]) next[key]=`${label} is required.`}); setErrors(next); if(Object.keys(next).length) return; setSubmitted(true); window.scrollTo({top:0,behavior:'smooth'}) }
  if(submitted) return <section className="success-state"><p className="eyebrow">REQUEST SENT</p><h2>Booking request received.</h2><p>Thanks — we'll contact you shortly to confirm your appointment.</p><a className="button secondary" href="index.html">Back to website</a></section>
  return <form onSubmit={submit} noValidate><fieldset><legend>Customer details</legend><div className="field-grid"><label>Full Name <i>*</i><input value={values.name} onChange={e=>set('name',e.target.value)} aria-invalid={!!errors.name} autoComplete="name" type="text" /><FieldError message={errors.name} /></label><label>Phone Number <i>*</i><input value={values.phone} onChange={e=>set('phone',e.target.value)} aria-invalid={!!errors.phone} autoComplete="tel" inputMode="tel" type="tel" /><FieldError message={errors.phone} /></label></div><label>Instagram Username <em>(optional)</em><input value={values.instagram} onChange={e=>set('instagram',e.target.value)} autoComplete="off" type="text" /></label></fieldset>
    <fieldset><legend>Vehicle details</legend><label>Vehicle Type <i>*</i><ShadSelect value={values.vehicle} onChange={v=>set('vehicle',v)} options={['Sedan','SUV','Truck','Van','Other']} placeholder="Select vehicle type" error={errors.vehicle} /></label></fieldset>
    <fieldset><legend>Service selection</legend><div className="field-grid"><label>Package <i>*</i><ShadSelect value={values.package} onChange={v=>set('package',v)} options={['Gold','Titanium']} placeholder="Select package" /></label><label>Service Type <i>*</i><ShadSelect value={values.serviceType} onChange={v=>set('serviceType',v)} options={['Interior','Full']} placeholder="Select service type" /></label></div><div className="price-selected"><span>Selected service <small>Same price for all vehicle sizes.</small></span><strong>{values.package} {values.serviceType} — ${prices[values.package][values.serviceType]}</strong></div></fieldset>
    <fieldset><legend>Location</legend><div className="field-grid"><label>Service Location / Area <i>*</i><input value={values.location} onChange={e=>set('location',e.target.value)} aria-invalid={!!errors.location} autoComplete="address-level2" type="text" /><FieldError message={errors.location} /></label><div className="radio-field"><span>Preferred Service Type <i>*</i></span><div className="radio-options"><label><input checked={values.serviceLocation==='Mobile'} onChange={()=>set('serviceLocation','Mobile')} type="radio" name="serviceLocation" /> Mobile</label><label><input checked={values.serviceLocation==='Shop'} onChange={()=>set('serviceLocation','Shop')} type="radio" name="serviceLocation" /> Shop</label></div><FieldError message={errors.serviceLocation} /></div></div></fieldset>
    <fieldset><legend>Scheduling</legend><div className="field-grid"><label>Preferred Date <i>*</i><DatePicker value={values.date} onChange={v=>set('date',v)} error={errors.date} /></label><label>Preferred Time <i>*</i><ShadSelect value={values.time} onChange={v=>set('time',v)} options={timeOptions} placeholder="Select a time" error={errors.time} /></label></div><label>Additional Notes <em>(optional)</em><textarea value={values.notes} onChange={e=>set('notes',e.target.value)} placeholder="Do you have water and electrical supply handy?" rows="3" /></label></fieldset><button className="button primary submit" type="submit">Request booking</button><p className="submit-note">We'll review your request and confirm availability.</p></form>
}
createRoot(document.getElementById('bookingFormRoot')).render(<BookingForm />)
